### ISSUE TITLE
Request: Pass in name of changed file as argument to the invoked executable

### ISSUE THREAD

**Issue by craftytrickster** [mattgreen/watchexec#11]
I just tried out this program, and it has worked very well, so thanks!

It would be very useful if we can actually pass in the name of the changed file as an argument to the executable that you are invoking, perhaps by adding a new flag like -n (or perhaps another char)

For example, if I have a shell script (called myscript.sh) that says `echo "The following file has been changed: $1"` I would like to be able to do the following:

`watchexec -n $WATCH_DIR myscript.sh`

If file foo in the $WATCH_DIR has been changed, I would want to see the following appear on my screen:

"The following file has been changed: foo".

To give some background, the reason I want to do this specifically is to run watchexec and rsync on a folder of repositories, which I would like to watch. However, most of the time I am only working on a single repo, so if a change occurs in a repo folder, I would prefer to pass that folder in as an argument to rsync, to make it more efficient (since this is over ssh).

**Comment by mattgreen** [comment]
What if I set an environment variable in the child process launched by `watchexec`? I'm envisioning this use case looking like this:

`$ watchexec "echo $WATCHEXEC_FILE modified"

That way, the usage stays simple but you still have access to it. The downside is it's harder to discover; that could be remedied by expanding the help screen and adding a manpage.

**Comment by craftytrickster** [comment]
Sounds great to me!

**Comment by mattgreen** [comment]
One subtlety here: it's possible you'll see files that don't exist as $WATCHEXEC_UPDATED_PATH; these are temp files created by your editor. If this is the case, you'll want to filter or wait for the commit that puts multiple files in there and search for one in there that matches.
