### ISSUE TITLE
gitignore and globsets

### ISSUE THREAD

**Issue by BurntSushi** [mattgreen/watchexec#14]
Handling `gitignore` correctly is hard, and has been one of the larger sources of bugs in my own project. I'm currently working on splitting the `gitignore` logic into its own separate crate, including support for parent directories, global ignores and even `.git/info/exclude`. It will also be stupidly fast.

In the interim, you might find  the [`globset`](https://docs.rs/globset/0.1.0/globset/) crate helpful, which I built explicitly for this purpose. When you get users that [work on projects with large `.gitignore` files](https://github.com/mysql/mysql-server/blob/5.7/.gitignore), they will thank you for using `globset`. :-)

Anyway, just thought I'd give you a friendly heads up. If you like, I can ping you again when I get the `gitignore` logic split out. I'm also reaching out to find out if you have any peculiar use cases that might be worth considering as I go through the process!

In any case, nice project!

**Comment by mattgreen** [comment]
First off, thanks for `ripgrep`; I copied a bunch of CI stuff out of it to get going.

Second, that `.gitignore` example file is a nightmare. Wow.

Third, I'd love to use your `gitignore` crate. The only weird use case I have is my implementation pretty much ignores the "only match if directory" rule because I sometimes deal with paths that don't exist by the time I'm checking on their status, but I still need to be able to make a determination on whether I should act on them.

I've done some thinking on this, and I'm OK with shirking this correctness requirement, because I can't come up with a case where a build setup generates a file instead of a directory of the same name and I incorrectly assume the file is excluded. (In other words, it feels more pathological than plausible, especially for a dev-oriented tool; feel free to correct me if you have a counter-example!)

The last time I checked your `gitignore.rs` module, you could pass in true/false for whether it's a directory, thus rendering the function free of side effects. That's all I'm looking for. I can decide whether to fudge such cases on my end. I just don't want to see the exclusion check fail completely due to the directory check failing.

**Comment by BurntSushi** [comment]
Sounds great! Indeed, all of the ignore checking would be side effect free because of that second is_dir parameter.

My secondary goal in all of this is to provide a parallel recursive directory iterator that respects ignore patterns, which I hope will also be split out into this new ignore crate. Of course, lower level components will be exposed as well, all the way down to globsets.

FWIW, if I did my job right, it should be relatively easy for you to replace your Vec<Pattern> with a GlobSet and get a nice win. :-)

I'll check back in when I have something more for you to look at. Thanks for responding!

P.S. I got my ci stuff from the rust-everywhere project. I highly recommend checking it out!

**Comment by BurntSushi** [comment]
This is what I have so far: https://github.com/BurntSushi/ripgrep/tree/master/ignore --- Hopefully docs.rs kicks back into gear soon so it's easier to browse the docs.

The API isn't perfect, and I would have liked to do better. Basically, there's a pretty big gap between "here's this high level recursive directory iterator that does everything for you" and "here are the raw matchers that you'll need to assemble yourself." If you can somehow use the former, than that would be ideal, but you should at least be able to replace your existing code with `ignore::gitignore::Gitignore` and not regress on anything.

**Comment by mattgreen** [comment]
Awesome, I will give this a shot this week.

**Comment by mattgreen** [comment]
Bumped into a few things when trying this out:

* `matched()` returned `Match::None` for a `.gitignore` file with a single pattern of "target" against the path "target/debug/watchexec". Will it be split out to its own repo soon? A failing testcase:

    ignored!(ig31, ROOT, "target", "target/debug/executable");

* `ripgrep` and `watchexec` could probably share logic to build a `Gitignore` out of the nearest `.gitignore` file, along with a `core.excludesfile`, if any.

**Comment by BurntSushi** [comment]
> matched() returned Match::None for a .gitignore file with a single pattern of "target" against the path "target/debug/watchexec".

The glob `target` (which is translated to `**/target` by `gitignore` rules) doesn't match `target/debug/watchexec`. It will match `target` however. I wonder if making this translate to `**/target/**` will fix things. (Which incidentally will regress performance for recursive iterators.)

> Will it be split out to its own repo soon? Only reason I ask is I'm not sure where to file an issue for this.

Dunno. Filing issues against the ripgrep repo seems fine.

> ripgrep and watchexec could probably share logic to build a Gitignore out of the nearest .gitignore file, along with a core.excludesfile, if any.

This is what `ignore::Walk` does.

I'm starting to worry that the `ignore` crate is very heavily geared towards users that are doing a recursive directory walk, and that supporting other use cases may be quite challenging.

**Comment by mattgreen** [comment]
That same case also tripped up the `gitignore` crate when I tried it.

> I'm starting to worry that the ignore crate is very heavily geared towards users that are doing a recursive directory walk, and that supporting other use cases may be quite challenging.

Yeah, I hear you, especially given that these are side projects for both of us.

If I were you, I'd just focus on retaining the low/high-level split you currently have. Users (such as myself) can write mid-level modules to fill in the gaps and tailor the project to what they need.

**Comment by BurntSushi** [comment]
FWIW, if making `target` be `**/target/**` instead of `**/target` is all that's needed, then I'd be more than happy to support that as an option on `GitignoreBuilder`. It's will probably be a source of confusion, but if that's all you need to reuse something from the `ignore` crate, then it seems worth it.

**Comment by mattgreen** [comment]
I'd appreciate that!

The gitignore docs are underspecified. They use the word pattern throughout, but make mention of pathspec in this particular case, and the behavior exhibited by `git-check-ignore` certainly fits that of pathspec.

**Comment by BurntSushi** [comment]
Which part of the docs are you referring to? (I see one mention of `pathspec` in `man gitignore` but it looks unrelated?)

To be clear, the path you have absolutely should be ignored. If you use `ignore::Walk`, then it will never descend into the `target` directory.

**Comment by mattgreen** [comment]
The discussion of handling patterns with slashes mentions pathspecs in passing; I interpreted that as saying the similarities in semantics are intentional, and suggesting there might be additional fallout from that, like what we see here.

I see what you mean about use cases diverging.

**Comment by mattgreen** [comment]
My WIP: https://github.com/mattgreen/watchexec/blob/1ba685912f3595b4a044beae4912cd5fdd033341/src/ignore.rs#L34-L35

I need to refine when it does that potentially.

I get the following debug output:
    glob converted to regex: Glob { glob: "**/target/**/*", re: "(?-u)^(?:/?|.*/)target(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true }, tokens: Tokens([RecursivePrefix, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t'), RecursiveZeroOrMore, ZeroOrMore]) }

I expected to see `**/target/**` there, but it seems to work okay in practice.

**Comment by mattgreen** [comment]
For now I'll continue to maintain a more general ignore implementation that is tailored to my needs. Perhaps in the future we can figure out a perfect zero-cost abstraction that fits everyone's requirements. :)
