### ISSUE TITLE
Debounced Watch

### ISSUE THREAD

**Issue by craftytrickster** [mattgreen/watchexec#15]
How open are you to the idea of a batched/debounced watch, where the user specifies a time period (for example) 500milliseconds and the following behavior would occur:

User edits a file at 0ms, initiating the 500ms countdown.
At 500ms, the watchexec executes its target command.

User edits a file at 0ms, initiating the 500ms countdown.
User edits a file at 100ms, resetting the 500ms countdown.
User edits a file at 150ms, resetting the 500ms countdown.
Finally, after no use, at 650ms, the watchexec executes the target command.

This would be valuable for me for use in rsync, for example, on a git clone a ton of files are edited at once, and I would not want the target rsync to be executed until the folder is cloned.

To tie this to my other issue here - https://github.com/mattgreen/watchexec/issues/11, perhaps the debounced watch can add a comma separated string of all of the edited files at $WATCHEXEC_FILE.

If you are not open to such a thing, that would be fine too, I just would like to know in case I have time at some point to do a PR.

**Comment by mattgreen** [comment]
While the debounce algorithm is very simple and suitable for 1.0. It definitely needs refinement.

Like you outlined, I'd like to see wait until FS activity cools off. Thinking out loud, would we want a deadline that acts as a failsafe? Under constant activity, a naive debouncing algorithm would effectively never end.

A deadline would also help when we reported on what files changed via env vars. I'm a bit concerned about bumping into env var limits; mostly on [Windows](https://blogs.msdn.microsoft.com/oldnewthing/20100203-00/?p=15083). I think what I'd do here is make $WATCHEXEC_FILE contain the first file that changed, and $WATCHEXEC_FILES contain all files changed in this notification, separated by the path separator for the platform.

I'll take a stab at this this weekend, though I'll likely break some of these features apart for testing.

**Comment by craftytrickster** [comment]
If you want someone to take a look or review or possibly help, let me know.

**Comment by craftytrickster** [comment]
If you are concerned about variables lengths, as a compromise maybe you can set $WATCHEXEC_UPDATED_PATH to the value of the longest common subpath of the list of variables. See https://docs.python.org/3/library/os.path.html#os.path.commonpath for an example.

**Comment by mattgreen** [comment]
There's been some movement on this, so please review it and let me know what you think: https://github.com/mattgreen/watchexec/commit/0e0d14b475030eb47cd6d388178f1ccfdaed5d4c

Note that the main loop is a bit more complicated now as we need to react to signals (conveyed via `interrupt_rx`) in a timely fashion.

**Comment by craftytrickster** [comment]
I just added one comment about perhaps allowing this to be toggleable, in case some one does not want this batching type processing. I will give it a try later and I will let you know how it goes.

**Comment by craftytrickster** [comment]
I just downloaded the lastest using cargo install watchexec (1.1.1) and it seems now that it is only firing on files that already exist.

For example, if I add a new file to the watched directory, nothing happens. However, if I touch/edit that file, I only then see the watchexec fire. Likewise, if I delete the file, nothing happens either. I would expect watchexec to fire on all of these scenarios.

**Comment by mattgreen** [comment]
Interesting. What OS? Does it occur on 1.0? Do you have a small test case I could try?

**Comment by mattgreen** [comment]
I was able to replicate this. 1.1/1.1.1 was a clunker of a release, so I've yanked them from crates.io.

1.2 is up on Cargo with the batching in. I may wait until someone complains to default it off.

**Comment by craftytrickster** [comment]
Thanks a lot!

**Comment by passcod** [comment]
I'd be interested in how this compares with the new debounced API of Notify 3.0.0, if you're going to upgrade to that.

**Comment by mattgreen** [comment]
The plan is to get to Notify 3.x ASAP, as it's a critical dependency for watchexec.

Using raw mode we can tweak responsiveness quite a bit; whether it's actually any better than Notify is a legitimate question. Currently we wait until FS activity levels out over all watched directories after 500ms with no other deadline. Does Notify wait a finite amount of time and then stop, or does it wait until all FS activity has ceased? Both approaches have tradeoffs.

**Comment by passcod** [comment]
The first one, if I understand your question correctly. The delay is customisable, of course. The debounce is trailing-edge which is probably the biggest responsiveness factor there is, and I certainly appreciate that there are uses for raw mode.

It occurs to me you could possibly use the debounced API on a short delay (say, 100ms) to take advantage of the rename tracking and do some early debounce, and then re-debounce that to the granularity and responsiveness you need. I haven't really tested that, though, so it may be completely silly.
