### ISSUE TITLE
WATCHEXEC_UPDATED_PATH value

### ISSUE THREAD

**Issue by craftytrickster** [mattgreen/watchexec#19]
Currently, the $WATCHEXEC_UPDATED_PATH is simply set to the first filepath in the list of all of the files that were updated. 

I know that this is partially done to avoid running into issues with windows machines that enforce small variable limits.

I know that we had discussed perhaps making it a comma separated value of all the paths. Perhaps this is something that can be enabled for the non windows machines.

Another suggestion that I like that would fit both windows/unix is to set it to the longest common sub-path of all of the files that were updated. That way, you wouldn't have to worry about the variable size limits, but it would still provide useful information in the variable. However, doing that would require a bit of extra work.

**Comment by mattgreen** [comment]
Finding the common prefix would go a long way in helping. watchexec deals only in canonicalized paths, so everything gets expanded to the absolute path.

Finding the longest common substring is the hard part here, so I'll start poking at that.

**Comment by craftytrickster** [comment]
I don't mind adding that functionality myself in a PR, but I will need to find the time to implement it, unfortunately work has been busy. If you want to go for it, that's fine, but if not, maybe I can find some time this weekend.

**Comment by mattgreen** [comment]
Sounds good! No rush, have some fun with it!

**Comment by mattgreen** [comment]
FYI, be sure you're hacking on 1.2.2 (aka master), as paths could be duplicated in the updated file list returned from `wait()`, especially on Linux.

**Comment by craftytrickster** [comment]
Good to know, thanks. The method I plan on using dedupes by default anyway, so it wouldn't be an issue.
