### ISSUE TITLE
100% CPU all the time

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#25]
On `1.2` and `1.3`, `watchexec` is at 100% CPU and doesn't launch the command. It also does that in an empty directory. `SIGINT` and `SIGTERM` does nothing, I have to send `SIGKILL`.

**Comment by mattgreen** [comment]
A few questions:

* what OS and OS version?
* how did you install it? (Cargo, etc)
* what command line are you calling it with?

Finally, re-run this case with `--debug` on the command line and paste the output here.

**Comment by Yamakaky** [comment]
- `watchexec 1.3.0`
- Archlinux
- `watchexec ls` in an empty directory (doesn't matter which command I specify, though)
- `--debug` doesn't do anything

Using `perf top`, I can see that it seems to be blocked with calls like `std::Path::exists` and `std::path::Components::as_path`.

**Comment by mattgreen** [comment]
Thanks for reporting this, I think most people were using this in developer workflows so they never ran into it.

**Comment by mattgreen** [comment]
Fixed in 1.4.0, which is available on Cargo.

**Comment by Yamakaky** [comment]
Oh, I see, so it searched `/../../../../../.gitignore` XD
Works, thanks!
