### ISSUE TITLE
Watch other directory

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#27]
Use case:

- I build a binary in a/
- I launch watchexec in b/

I want watchexec to watch a/ and b/. I think a switch to add an other file/directory would be fine.

**Comment by mattgreen** [comment]
This used to exist, but it raises lots of questions about semantics. For example, when you watch a/ and b/, where do you load ignore files from?

Right now you can launch watchexec twice to cover this scenario.

**Comment by Yamakaky** [comment]
Not really. My use case is that I build rustc in it's source directory, and use it to build a crate. I could add a symlink in the crate directory to the source directory, but that's not really convenient.

**Comment by mattgreen** [comment]
Okay, I'm on board with working on this. I'm going to take it slow to make sure the ignore file handling is sane, however. Look for it in 1.7.

**Comment by Yamakaky** [comment]
Cool!
Just so that you know: I use `watchexec` even when not programming like latex. I even find it better that `carco watch` ;)

**Comment by anti-social** [comment]
We have similar issue in our project: there are several directories especially `node_modules` and `.vagga` with a lot of subdirectories (up to 100K and more). So it would be nice to be able to run `watchexec` with specific directories and files to reduce number of watches.

Possibly there should be `--watch-dir` option (and opposite `--no-watch-dir`).

**Comment by mattgreen** [comment]
Noted. The ignore functionality is in a much better place now and that was the primary blocker for this task. Will try to hack on it this weekend.

**Comment by mattgreen** [comment]
As of e16a6b3a24f8661d214a547a992847b13ea9f410, this is supported. `.gitignore` files are loaded from each watched path, and path filtering only consults the `.gitignore` files that cover those paths.

I need to update docs, but if you want to try it out early you can pull from master. This will be in 1.7.0.

**Comment by Yamakaky** [comment]
You rock!

**Comment by mattgreen** [comment]
1.7.0 has been pushed to Cargo.

**Comment by anti-social** [comment]
Just recently we've used watchexec in our company. Thank you!

**Comment by mattgreen** [comment]
Glad to hear it! Let me know if there are other things that keep you from being productive with watchexec!

**Comment by sergeevabc** [comment]
Another non-obvious thing to grasp is how to watch the folder _without watching its subfolders_?
