### ISSUE TITLE
Pass arguments to the command

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#28]
$ watchexec -c ls -l
    argument '-l' wasn't expected
    $ watchexec -c 'ls -l'

It would be cool if I didn't have to use `'`.

**Comment by mattgreen** [comment]
This is a bug, I'll look into it. Thanks!

**Comment by Mange** [comment]
@yamakaky you can also separate options from the rest using the UNIX convention "--". :-) 

    watchexec -c -- ls -l

**Comment by Yamakaky** [comment]
Oh yeah, right
