### ISSUE TITLE
Handle SIGCHLD

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#29]
`watchexec` waits for a filesystem event to collect zombie processes, instead of collecting them on `SIGCHLD`.

**Comment by mattgreen** [comment]
I agree it is suboptimal.

However, I've yet to find a solution to this that doesn't make the resulting code way more complicated.

**Comment by Yamakaky** [comment]
The zombie process doesn't use resources and is collected at the next round, so it's low priority.

**Comment by mattgreen** [comment]
Fixed in b2c809c87a9332ea6666ab5d6e441fac03213d2e.

Needs more testing in day-to-day use and development, but it will be in 1.7.

**Comment by Yamakaky** [comment]
Cool!
