### ISSUE TITLE
Propagate SIGTSTP (Ctrl-Z) to children

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#30]

**Comment by mattgreen** [comment]
This implies we handle SIGCONT as well. I like this idea and will look into it.

**Comment by mattgreen** [comment]
Added this in 154c23a5a4fcfc25cb34087ff4dc370897f549cf

Please clone from master and give it a try. If it looks good I'll release 1.6.0 with it next week.

**Comment by Yamakaky** [comment]
Seems good!
