### ISSUE TITLE
Submit to Homebrew Core

### ISSUE THREAD

**Issue by mattgreen** [mattgreen/watchexec#32]
I'd really like to see watchexec in Homebrew proper, as it is mostly feature-complete and quite stable with a slowed release schedule. However, given Homebrew's [Acceptable Formulae](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) doc:

> We frown on authors submitting their own work unless it is very popular.

If someone would like to do this (and, in a way, vouch for the project), please chime in here. Thanks!

**Comment by sbdchd** [comment]
I made a PR to [homebrew-core][1].

[1]: https://github.com/Homebrew/homebrew-core/pull/8833

**Comment by mattgreen** [comment]
Thanks @sbdchd!
