### ISSUE TITLE
Notification on command end

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#38]
A lot of programs don't show when they end. It's OK in the console when you have the prompt, but it can be hard to see with watchexec. I'm thinking maybe adding a switch that prints "End of execution" or simply "---------".

**Comment by mattgreen** [comment]
My first thought is to suggest using `--clear` to clear the terminal.

If that doesn't do it for you, I prefer using Unix's powers of composition to get what you want: `watchexec "make; echo ----------------"`

You can alias the `echo` part to `hr` or the like to make it terse.
