### ISSUE TITLE
Configurable debounce / cool-off

### ISSUE THREAD

**Issue by kamalmarhubi** [mattgreen/watchexec#51]
This is the next step from #15, which was implemented in 0e0d14b475030eb47cd6d388178f1ccfdaed5d4c. I'd like to be able to configure this. 500ms is way too slow for me, I'd like something closer to 100ms to be settable.

I'm not sure what the best name for this flag would be. `--debounce` perhaps? `d` is taken for `--debug`, but perhaps that could be moved to some level of `-v | --verbose`. Let me know what you think, I'm happy to send a short PR for this.

**Comment by mattgreen** [comment]
Those changes sound good. I don't mind changing the meaning of `-d` as it is not a setting people will use often.

**Comment by jaemk** [comment]
I'd like to implement this. Just want to confirm, you're alright with re-purposing `-d` to pair with `-d, --debounce`?

**Comment by mattgreen** [comment]
Great! Current use of `-d` can move to `-v`/`--verbose`.

**Comment by mattgreen** [comment]
Closed by #64; thanks @jaemk!
