### ISSUE TITLE
Constant reloading

### ISSUE THREAD

**Issue by VShell** [mattgreen/watchexec#54]
I'm running watchexec in a Docker container on Docker for Mac in a directory that's bound to my code directory. The removal of the \*/.\*/\* ignore seems to cause watchexec to think something is constantly being updated, in the following command:

`watchexec -i target -r cargo run`

Changing that command to:

`watchexec -i target -i \*/.\*/\* -r cargo run`

Solves the issue. I can't figure out what files this is matching that might be being modified, though - even individually ignoring all the results of `find . -name .\*` in the same container doesn't help.

Is there any obvious debugging I can do to track this down?

**Comment by mattgreen** [comment]
Run with the `--debug` flag to see what it is triggering file notifications.

**Comment by VShell** [comment]
Apparently it's index.lock under `.git` (`*** Path updated: "/code/.git/index.lock"`) - but running `watchexec -i target -i .git --debug -r cargo run` results in the same behaviour, despite the file changes under `target` being properly ignored and `.git` being added to the ignore list in the same way according to the logs.

**Comment by VShell** [comment]
The first bit of output:

```
$ docker-compose run idp watchexec -i target -i .git --debug -r cargo run
*** glob converted to regex: Glob { glob: "**/target/**", re: "(?-u)^(?:/?|.*/)target(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: true }, tokens: Tokens([RecursivePrefix, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t'), RecursiveSuffix]) }
*** built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
*** Loaded "/code/.gitignore"
*** Adding ignore: "*/.DS_Store"
*** Adding ignore: "*.pyc"
*** Adding ignore: "*.swp"
*** Adding ignore: "target"
*** Adding ignore: ".git"
*** built glob set; 2 literals, 0 basenames, 2 extensions, 0 prefixes, 1 suffixes, 0 required extensions, 0 regexes
*** Watching "/code"
*** Assembled command "sh" "-c" "cargo run"
*** Waiting for filesystem activity
```

**Comment by mattgreen** [comment]
`index.lock` can change due to a shell prompt or other program querying git.

To fix, I added `.git`, `.hg`, and `.svn` to the default ignore list. This will be in version 1.8.2.
