### ISSUE TITLE
doesn't seem to run command when files are changed (Windows 10)

### ISSUE THREAD

**Issue by radix** [mattgreen/watchexec#55]
Hi, I'm trying `watchexec` for the first time. I'm on Windows 10, running watchexec from PowerShell. I installed watchexec with `cargo install watchexec`.

```
C:\Users\radix\Projects\pandt [master ↑ +1 ~1 -0 !]> watchexec --version
watchexec 1.8.3
C:\Users\radix\Projects\pandt [master ↑ +1 ~1 -0 !]> watchexec -- dir
 Volume in drive C is Blade
 Volume Serial Number is B83C-EF1B

 Directory of C:\Users\radix\Projects\pandt
```

(directory contents elided)

now, in another PowerShell instance:

```
C:\Users\radix> cd .\Projects\pandt\
C:\Users\radix\Projects\pandt [master ↑ +1 ~1 -0 !]> echo foo > bar
C:\Users\radix\Projects\pandt [master ↑ +2 ~1 -0 !]> ls bar


    Directory: C:\Users\radix\Projects\pandt


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/4/2017  11:21 PM             12 bar
```

back in my original terminal where I'm running `watchexec`, there's still only the one instance of output from `dir`.

So watchexec is running the program initially, but doesn't seem to trigger the command when files are changed.

**Comment by radix** [comment]
by the way, I just tested using `--no-default-ignore` and it didn't change anything.

**Comment by radix** [comment]
I tried enabling debugging and I'm seeing something strange. This time I used a simple `echo` command to minimize output:

```
C:\Users\radix\Projects\pandt [master ↑ +1 ~1 -0 !]> watchexec -d --no-default-ignore -- echo hi
*** glob converted to regex: Glob { glob: "**/target/**", re: "(?-u)^(?:/?|.*/)target(?:/?|/.*)$", opts: GlobOptions { c
ase_insensitive: false, literal_separator: true }, tokens: Tokens([RecursivePrefix, Literal('t'), Literal('a'), Literal(
'r'), Literal('g'), Literal('e'), Literal('t'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**/saved-game.yaml/**", re: "(?-u)^(?:/?|.*/)saved\\-game\\.yaml(?:/?|/.*)$",
 opts: GlobOptions { case_insensitive: false, literal_separator: true }, tokens: Tokens([RecursivePrefix, Literal('s'),
Literal('a'), Literal('v'), Literal('e'), Literal('d'), Literal('-'), Literal('g'), Literal('a'), Literal('m'), Literal(
'e'), Literal('.'), Literal('y'), Literal('a'), Literal('m'), Literal('l'), RecursiveSuffix]) }
*** built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 2 regexes
*** Loaded "\\\\?\\C:\\Users\\radix\\Projects\\pandt\\.gitignore"
*** Watching "\\\\?\\C:\\Users\\radix\\Projects\\pandt"
*** Assembled command "cmd.exe" "/C" "echo hi"
*** Waiting for filesystem activity
hi
*** Path updated: "\\\\?\\C:\\Users\\radix\\Projects\\pandt\\bar"
*** Waiting for process to exit...
```


At the end there, I ran `echo foo > bar` in another terminal, and I see that watchexec noticed the filesystem change. Then it says "Waiting for process to exit", which seems odd, since `echo hi` should exit immediately.

So I added a `-r` to the command line and now it works pretty reliably. So I guess the bug here is in Windows process-management; it doesn't seem to be noticing subprocesses exiting (or allowing them to exit?).

**Comment by radix** [comment]
Another data point: I wondered if it was the shell-running code specifically that was buggy, so I tried using `-n` with an executable file (`echo.exe` from msys), but it exhibits the same behavior of waiting for the process to exit. So I don't believe it's the shell-running code.

**Comment by mattgreen** [comment]
Hey @radix, thanks for reporting this. Since my main OS is macOS stuff like this can slip through sometimes :(. I will boot up my Boot Camp VM today and give this a shot. Hoping it is something silly.

**Comment by mattgreen** [comment]
Yeah, I replicated this. Definitely a dumb bug. I think I'm going to have to update the use of Win32 job objects to fix this. In the meantime you can use `--restart` to avoid the bug at the cost of possibly re-running things when you weren't quite ready.

**Comment by mattgreen** [comment]
This should be fixed in 1.8.4, which I've just pushed to Cargo. Give it a try!

**Comment by radix** [comment]
Sorry for the delay in response @mattgreen: I've now tested it and it works great. Thanks for your work on this issue!

**Comment by mattgreen** [comment]
No problem. Glad it works for you! Thanks for the heads up on the bug.
