### ISSUE TITLE
Windows 7 Access Denied Error 5

### ISSUE THREAD

**Issue by Henning-K** [mattgreen/watchexec#56]
As discovered through `cargo-watch` ( [corresponding issue](https://github.com/passcod/cargo-watch/issues/69) ) if `watchexec` is used from inside another job on Windows 7, the [`AssignProcessToJobObject`](https://github.com/mattgreen/watchexec/blob/master/src/process.rs#L190) API call return 0 because of an "Access Denied (OS Error 5)".

Apparently this issue is fixed from Windows 8 onward but when you use nested jobs like this on Windows 7 it will not work.

**Comment by mattgreen** [comment]
This is going to be extremely difficult to fix. `watchexec` needs to use job objects to watch the entire process tree, especially when doing server development, so it uses job objects to do so. Given the age of Windows 7, and the API's limitation, I don't see a way to fix this well.

**Comment by mattgreen** [comment]
As a consolation, you can see if 1.2.0 has enough features for you to use:

https://github.com/mattgreen/watchexec/releases/tag/1.2.0

**Comment by lamarqua** [comment]
You should probably mention in the README that this doesn't run on Windows 7.

**Comment by sergeevabc** [comment]
By the way, when I launch ```watchexec echo hello``` on Windows 7, the output ```hello``` goes immediately, however there are no changed files to trigger it.

**Comment by passcod** [comment]
Yes, that is the default behaviour. Use `--postpone` to disable run-at-start.
