### ISSUE TITLE
Cannot build on rustc 1.15.1

### ISSUE THREAD

**Issue by hcpl** [mattgreen/watchexec#57]
The API of `Command::args` that `watchexec` relies upon was introduced in Rust 1.16:
- [1.15.1 `Command::args`](https://doc.rust-lang.org/1.15.1/std/process/struct.Command.html#method.args);
- [1.16.0 `Command::args`](https://doc.rust-lang.org/1.16.0/std/process/struct.Command.html#method.args).

So either update README to reflect this change or revert/modify https://github.com/mattgreen/watchexec/commit/f88f1b36c31a62e4dcf92e8601a823a43846d6ce.

**Comment by mattgreen** [comment]
Fixed, thanks.
