### ISSUE TITLE
--ignore not working as expected

### ISSUE THREAD

**Issue by georgecrawford** [mattgreen/watchexec#66]
Hi,

Thanks for this great library. It's very nearly perfect for my use cases.

I've found that the `--ignore` parameter doesn't work as I'd expect. The documentation isn't clear about exactly what a 'path' or a 'pattern' means (`Ignore modifications to paths matching the pattern`), but I would expect a filename to be correctly ignored:

```bash
watchexec --no-default-ignore --no-vcs-ignore --verbose --ignore test.json 'echo "touching now"; touch test.json; sleep 1'
```
This results in an infinite loop:

```
$ watchexec --no-default-ignore --no-vcs-ignore --verbose --ignore test.json 'echo "touching now"; touch test.json; sleep 1'
*** Adding ignore: "test.json"
*** built glob set; 1 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
*** Watching "/Users/george/Desktop/watchexec-test"
*** Assembled command "sh" "-c" "echo \"touching now\"; touch test.json; sleep 1"
*** Waiting for filesystem activity
touching now
*** Path updated: "/Users/george/Desktop/watchexec-test/test.json"
*** Waiting for process to exit...
*** Received SIGCHLD
*** Launching child process
*** Assembled command "sh" "-c" "echo \"touching now\"; touch test.json; sleep 1"
*** Waiting for filesystem activity
touching now
*** Path updated: "/Users/george/Desktop/watchexec-test/test.json"
*** Waiting for process to exit...
*** Received SIGCHLD
*** Launching child process
*** Assembled command "sh" "-c" "echo \"touching now\"; touch test.json; sleep 1"
*** Waiting for filesystem activity
touching now
*** Path updated: "/Users/george/Desktop/watchexec-test/test.json"
*** Waiting for process to exit...
*** Received SIGCHLD
*** Launching child process
*** Assembled command "sh" "-c" "echo \"touching now\"; touch test.json; sleep 1"
*** Waiting for filesystem activity
touching now
*** Path updated: "/Users/george/Desktop/watchexec-test/test.json"
*** Waiting for process to exit...
^C*** Received SIGINT
*** Sending SIGINT (int: 2) to child process
```

I can get the `--ignore` to match with a full absolute path (`--ignore $(pwd)/test.json`), but this slightly defeats the point of it being a 'pattern'.

Am I missing something obvious here?

**Comment by mattgreen** [comment]
Most of the ignore functionality is oriented towards excluding generated artifacts from build tools via glob patterns, rather than single files. That informs the parlance and the bug you ran into. I was able to replicate this successfully with a unit test in `NotificationFilter` but I need to think more on how to handle relative paths in that module in general.

Thanks for the report!

**Comment by georgecrawford** [comment]
Thanks. So are there any options I can use for a working glob pattern other than `$(pwd)/test.json`?

**Comment by mattgreen** [comment]
Not out of the box. (You could probably say `**/test.json` but that isn't buying you much.)

Will keep poking at it.

**Comment by Boscop** [comment]
It doesn't even work for me with a single filename that I want to ignore:
https://github.com/passcod/cargo-watch/issues/82
Am I doing something wrong?

**Comment by mattgreen** [comment]
@georgecrawford, I just pushed a possible fix to master. Give it a shot and let me know if it fixes your problem!

**Comment by georgecrawford** [comment]
Awesome. That seems to have fix the issue as described in this thread. Could you ping this thread again when this gets released? Thanks so much for the fix.

**Comment by mattgreen** [comment]
1.8.6 was pushed to Cargo just now. On macOS, it is awaiting approval from Homebrew.

Thanks for reporting the bug and confirming the fix.
