### ISSUE TITLE
Run multiple commands

### ISSUE THREAD

**Issue by Michael-F-Bryan** [mattgreen/watchexec#68]
At the moment `cargo watch` tries to execute multiple commands by joining them with `&&` into one long string (e.g. `cargo build && cargo test && cargo doc --quiet`). What are your thoughts on tweaking [`watchexec::cli::Args`] so it takes a list of commands to run, instead of just a single command?

i.e. Something like this:

```diff
 pub struct Args {
-   pub cmd: String,
+   pub cmd: Vec<String>,
    pub paths: Vec<String>,
    ...
```

cc: passcod/cargo-watch#80

[`watchexec::cli::Args`]: https://docs.rs/watchexec/1.8.5/watchexec/cli/struct.Args.html

**Comment by mattgreen** [comment]
I read the issue that prompted this, and it is a legit need, but running multiple commands is something the shell already does. I'd rather investigate ways to make that happen via the shell. Most likely this would be a platform check before building the command line that is passed to watchexec.
