### ISSUE TITLE
Make available on crates.io for installation using cargo

### ISSUE THREAD

**Issue by robinst** [mattgreen/watchexec#8]
Hey, this looks like a cool project! I'm currently using `entr`, but this looks nicer.

Did you think about publishing this on crates.io? That way, another way to install it is to run `cargo install watchexec` for users that already have Rust setup (and it works on every platform).

**Comment by mattgreen** [comment]
Good idea! I will get moving on this.

**Comment by mattgreen** [comment]
Done! That was easy. Thanks for the issue. :)

**Comment by robinst** [comment]
Nice :)!
